### PR TITLE
fix: Returning error when uri transport is different from supported.

### PR DESCRIPTION
**Pull request by lzielezinska**

### CODE REVIEW

**Review by thomasklein94 — APPROVED** [review]

**Comment by thomasklein94** [comment]
Thank you for your contribution

**Comment by lzielezinska** [comment]
hi, I don't have enough permissions to merge the PR, could  you do that?

**Comment by thomasklein94** [comment]
Of course, sorry. I've messed with the permissions and now its seems broken for some reason. 
Do you also need this to be released or is it okay if it's going to be released later with other features?

**Comment by paweltox** [comment]
@thomasklein94 if this is not a problem, we would like this to be released as well. Thank you.

**Comment by thomasklein94** [comment]
Sure thing, here is [`v0.3.4`](https://github.com/thomasklein94/packer-plugin-libvirt/releases/tag/v0.3.4) with @lzielezinska 's changes.
Thank you for your contributions :)

**Pull request merged**
